class raios {


public static int  main (String [] args){} //deteta
public static boolean policia (){}
public static double compiladores (){}
public static void compGrafica (){
System.out.println("String");
}

public static int buba;
public static int licious;
public static double aristo;
public static boolean cats;



public static int fim (){}


public static int  mano (){}
public static boolean police (String []args){} //não deteta!?

}
